"""initial schema

Revision ID: 0f52a83618c9
Revises: 
Create Date: 2026-09-24 21:07:52.001722

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database.models import JSONBOrJSON


revision: str = '0f52a83618c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reliability',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('latency_avg', sa.Float(), nullable=False),
    sa.Column('confidence_avg', sa.Float(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('false_negatives', sa.Integer(), nullable=False),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('true_negatives', sa.Integer(), nullable=False),
    sa.Column('invocations', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('last_invocation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reliability_agent_name'), 'agent_reliability', ['agent_name'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('incident_type', sa.String(length=128), nullable=True),
    sa.Column('affected_services', JSONBOrJSON(), nullable=False),
    sa.Column('raw_logs', JSONBOrJSON(), nullable=False),
    sa.Column('metrics', JSONBOrJSON(), nullable=False),
    sa.Column('traces', JSONBOrJSON(), nullable=False),
    sa.Column('topology', JSONBOrJSON(), nullable=False),
    sa.Column('context', JSONBOrJSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_idempotency_key'), 'incidents', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pattern_signature', sa.String(length=256), nullable=False),
    sa.Column('pattern_text', sa.Text(), nullable=False),
    sa.Column('root_cause_hint', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('incident_ids', JSONBOrJSON(), nullable=False),
    sa.Column('metadata', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_approved'), 'patterns', ['approved'], unique=False)
    op.create_index(op.f('ix_patterns_pattern_signature'), 'patterns', ['pattern_signature'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('predicted_failure_type', sa.String(length=256), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('impact', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'predicted_failure_type', name='_service_predicted_failure_type_uc')
    )
    op.create_index(op.f('ix_predictions_service'), 'predictions', ['service'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('finding_type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', JSONBOrJSON(), nullable=False),
    sa.Column('metadata', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_agent_name'), 'findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_findings_incident_id'), 'findings', ['incident_id'], unique=False)
    op.create_table('incident_memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('text_repr', sa.Text(), nullable=False),
    sa.Column('embedding', JSONBOrJSON(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lessons', JSONBOrJSON(), nullable=False),
    sa.Column('services', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_memory_incident_id'), 'incident_memory', ['incident_id'], unique=False)
    op.create_table('lessons_learned',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_learned_incident_id'), 'lessons_learned', ['incident_id'], unique=False)
    op.create_table('meta_reasoning_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('useful_agents', JSONBOrJSON(), nullable=False),
    sa.Column('unnecessary_agents', JSONBOrJSON(), nullable=False),
    sa.Column('optimal_path', sa.Text(), nullable=False),
    sa.Column('suggestions', JSONBOrJSON(), nullable=False),
    sa.Column('agent_scores', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_reasoning_records_incident_id'), 'meta_reasoning_records', ['incident_id'], unique=False)
    op.create_table('resolutions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('steps', JSONBOrJSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('metadata', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolutions_incident_id'), 'resolutions', ['incident_id'], unique=True)
    op.create_table('root_causes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alternatives', JSONBOrJSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('causal_chain', JSONBOrJSON(), nullable=False),
    sa.Column('contributing_factors', JSONBOrJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_causes_incident_id'), 'root_causes', ['incident_id'], unique=True)
    op.create_table('investigation_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('attempts_max', sa.Integer(), nullable=False),
    sa.Column('payload', JSONBOrJSON(), nullable=False),
    sa.Column('result_incident_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['result_incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_jobs_idempotency_key'), 'investigation_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_investigation_jobs_next_attempt_at'), 'investigation_jobs', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_result_incident_id'), 'investigation_jobs', ['result_incident_id'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_status'), 'investigation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_jobs_tenant_id'), 'investigation_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_jobs_tenant_id'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_status'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_result_incident_id'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_next_attempt_at'), table_name='investigation_jobs')
    op.drop_index(op.f('ix_investigation_jobs_idempotency_key'), table_name='investigation_jobs')
    op.drop_table('investigation_jobs')
    op.drop_index(op.f('ix_root_causes_incident_id'), table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index(op.f('ix_resolutions_incident_id'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_meta_reasoning_records_incident_id'), table_name='meta_reasoning_records')
    op.drop_table('meta_reasoning_records')
    op.drop_index(op.f('ix_lessons_learned_incident_id'), table_name='lessons_learned')
    op.drop_table('lessons_learned')
    op.drop_index(op.f('ix_incident_memory_incident_id'), table_name='incident_memory')
    op.drop_table('incident_memory')
    op.drop_index(op.f('ix_findings_incident_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_agent_name'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_predictions_service'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_patterns_pattern_signature'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_approved'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_idempotency_key'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_agent_reliability_agent_name'), table_name='agent_reliability')
    op.drop_table('agent_reliability')
    # ### end Alembic commands ###